name: CI

on:
  push:
    branches: ['main']

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: chainguard-dev/actions/setup-chainctl@main
        with:
          identity: 8c3a5484d4dab21a2c65244549dee4a668dabb09/fcae7a3c98194b38
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
      - run: |
          mvn compile jib:build -Djib.to.image=registry.enforce.dev/8c3a5484d4dab21a2c65244549dee4a668dabb09/recaptcha-jib-demo

